### PR TITLE
Peress/zephyr custom fake sig

### PR DESCRIPTION
**Pull request by yperess**
Pull the latest changes from FFF + a few extras that are still pending in https://github.com/meekrosoft/fff/pull/113

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
@yperess any chance you could merge the original tree instead of rebasing all the commits on top of the Zephyr one? That way it's clear that it tracks upstream

**Comment by yperess** [comment]
@fabiobaltieri this can now merge, could you review?

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri this can now merge, could you review?

Hey I still see the upstream commit rebased on top of the internal ones, could you merge them instead?

**Comment by yperess** [comment]
> > @fabiobaltieri this can now merge, could you review?
> 
> Hey I still see the upstream commit rebased on top of the internal ones, could you merge them instead?

Sorry, forgot `--force` on my push

**Comment by fabiobaltieri** [comment]
> Sorry, forgot `--force` on my push

Uhm... now there's only the revert?

**Comment by yperess** [comment]
> > Sorry, forgot `--force` on my push
> 
> Uhm... now there's only the revert?

I might have not understood what you wanted. I thought you wanted the revert. Then a pull request directly from the FFF repo instead of my own. I don't think I can do both in the same PR.

**Comment by fabiobaltieri** [comment]
> > > Sorry, forgot `--force` on my push
> > 
> > 
> > Uhm... now there's only the revert?
> 
> I might have not understood what you wanted. I thought you wanted the revert. Then a pull request directly from the FFF repo instead of my own. I don't think I can do both in the same PR.

Ok, yeah I thought single PR with revert + merge, but multiple PR works too.

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
